"""
RoseTrainer - Distributed Training Framework for Large Language Models

This module provides a comprehensive distributed training framework with support for:
- Multi-dimensional parallelism (TP, PP, DP, CP, EP)
- Memory optimization techniques
- Advanced communication patterns
"""

from .datasets import (  # Memory-mapped indexed datasets
    DistributedIndexedDataset,
    DType,
    IndexedDataset,
    IndexedDatasetBuilder,
    MMapIndexedDataset,
)
from .engine import RoseTrainer
from .fusions import (  # Fused operations
    FusedLayerNorm,
    InvalidConfigurationError,
    KernelNotAvailableError,
    LayerNormConfig,
    LayerNormException,
    LayerNormKernelType,
)
from .gradient import (  # Gradient finalization and decoupled storage
    BucketingStrategy,
    DecoupledGradientBuffer,
    DecoupledGradientConfig,
    DecoupledGradientManager,
    GradientBucket,
    GradientBucketConfig,
    GradientBucketManager,
    GradientFinalizationConfig,
    GradientFinalizer,
    GradientSyncStrategy,
    StorageMode,
    create_gradient_buckets,
)
from .monitoring import (  # Energy Monitoring System
    DistributedConfig,
    DistributedEnergyAggregator,
    DistributedEnergyMeasurement,
    EnergyMeasurement,
    EnergyMonitor,
    EnergyMonitoringConfig,
    EnergyMonitoringMode,
    FallbackStrategy,
    GPUEnergyTracker,
    GPUTrackerConfig,
    IntegrationConfig,
    ParallelismInfo,
    ParallelismType,
)
from .optimizer import (  # Distributed optimizer
    DistributedOptimizer,
    DistributedOptimizerConfig,
    ParameterPartitioner,
    ParameterRange,
)
from .parallelism import ColumnParallelLinear  # Parallelism components
from .parallelism import (
    DataParallelTrainer,
    MicrobatchInfo,
    NCCLConfig,
    ParallelismDimension,
    PipelineParallel,
    PipelineStage,
    RowParallelLinear,
    TensorParallelism,
    ZeROOptimizer,
    destroy_model_parallel,
    get_context_parallel_group,
    get_context_parallel_rank,
    get_context_parallel_size,
    get_data_parallel_group,
    get_data_parallel_rank,
    get_data_parallel_size,
    get_expert_model_parallel_group,
    get_expert_model_parallel_rank,
    get_expert_model_parallel_size,
    get_model_parallel_group,
    get_nccl_config,
    get_pipeline_model_parallel_group,
    get_pipeline_model_parallel_rank,
    get_pipeline_model_parallel_size,
    get_tensor_and_data_parallel_group,
    get_tensor_and_data_parallel_group_with_cp,
    get_tensor_model_parallel_group,
    get_tensor_model_parallel_rank,
    get_tensor_model_parallel_size,
    initialize_model_parallel,
    is_initialized,
    set_nccl_config,
)
from .random import (  # Multi-Parallel RNG State Management
    CudaRNGStatesTracker,
    RNGStateInfo,
    RNGStateType,
    checkpoint_parallel_rng_state,
    fork_parallel_rng_state,
    get_cuda_rng_tracker,
    get_parallel_rng_state,
    get_rng_state_summary,
    initialize_cuda_rng_tracker,
    model_parallel_cuda_manual_seed,
    parallel_rng_context,
    reset_cuda_rng_tracker,
    restore_parallel_rng_state,
    set_parallel_rng_state,
    synchronize_parallel_rng_states,
)
from .utils import (  # Gradient utilities
    GradientClipConfig,
    apply_gradient_clipping,
    calculate_gradient_norm_multitensor,
    check_gradient_finite,
    get_gradient_stats,
    gradient_accumulation_context,
    sync_gradients,
)

__all__ = [
    "RoseTrainer",
    # Memory-mapped indexed datasets
    "DType",
    "MMapIndexedDataset",
    "IndexedDataset",
    "IndexedDatasetBuilder",
    "DistributedIndexedDataset",
    # Data Parallel
    "DataParallelTrainer",
    # Model Parallel
    "TensorParallelism",
    "ColumnParallelLinear",
    "RowParallelLinear",
    # Pipeline Parallel
    "PipelineParallel",
    "PipelineStage",
    "MicrobatchInfo",
    # ZeRO
    "ZeROOptimizer",
    # Gradient Bucketing
    "BucketingStrategy",
    "GradientBucket",
    "GradientBucketConfig",
    "GradientBucketManager",
    "create_gradient_buckets",
    # Gradient Finalization
    "GradientFinalizationConfig",
    "GradientFinalizer",
    "GradientSyncStrategy",
    # Decoupled Gradient Storage
    "DecoupledGradientBuffer",
    "DecoupledGradientConfig",
    "DecoupledGradientManager",
    "StorageMode",
    # Gradient Utilities
    "GradientClipConfig",
    "apply_gradient_clipping",
    "calculate_gradient_norm_multitensor",
    "check_gradient_finite",
    "gradient_accumulation_context",
    "get_gradient_stats",
    "sync_gradients",
    # Distributed Optimizer
    "DistributedOptimizer",
    "DistributedOptimizerConfig",
    "ParameterPartitioner",
    "ParameterRange",
    # Parallel State Management
    "initialize_model_parallel",
    "is_initialized",
    "destroy_model_parallel",
    "get_tensor_model_parallel_group",
    "get_pipeline_model_parallel_group",
    "get_data_parallel_group",
    "get_context_parallel_group",
    "get_expert_model_parallel_group",
    "get_tensor_model_parallel_size",
    "get_pipeline_model_parallel_size",
    "get_data_parallel_size",
    "get_context_parallel_size",
    "get_expert_model_parallel_size",
    "get_tensor_model_parallel_rank",
    "get_pipeline_model_parallel_rank",
    "get_data_parallel_rank",
    "get_context_parallel_rank",
    "get_expert_model_parallel_rank",
    "get_model_parallel_group",
    "get_tensor_and_data_parallel_group",
    "get_tensor_and_data_parallel_group_with_cp",
    "NCCLConfig",
    "ParallelismDimension",
    "set_nccl_config",
    "get_nccl_config",
    # Fused Operations
    "FusedLayerNorm",
    "LayerNormConfig",
    "LayerNormKernelType",
    "LayerNormException",
    "KernelNotAvailableError",
    "InvalidConfigurationError",
    # Multi-Parallel RNG State Management
    "CudaRNGStatesTracker",
    "RNGStateInfo",
    "RNGStateType",
    "get_cuda_rng_tracker",
    "reset_cuda_rng_tracker",
    "initialize_cuda_rng_tracker",
    "model_parallel_cuda_manual_seed",
    "get_parallel_rng_state",
    "set_parallel_rng_state",
    "fork_parallel_rng_state",
    "checkpoint_parallel_rng_state",
    "restore_parallel_rng_state",
    "synchronize_parallel_rng_states",
    "get_rng_state_summary",
    "parallel_rng_context",
    # Energy Monitoring System
    "EnergyMonitor",
    "EnergyMonitoringConfig",
    "EnergyMonitoringMode",
    "GPUEnergyTracker",
    "DistributedEnergyAggregator",
    "EnergyMeasurement",
    "DistributedEnergyMeasurement",
    "FallbackStrategy",
    "GPUTrackerConfig",
    "DistributedConfig",
    "IntegrationConfig",
    "ParallelismType",
    "ParallelismInfo",
]
