"""Constants for RoseTrainer configuration and training.

This module defines all magic numbers and constants used throughout the RoseTrainer
implementation to improve maintainability and configurability.
"""

# Training defaults
DEFAULT_BATCH_SIZE = 32
DEFAULT_NUM_EPOCHS = 3
DEFAULT_SEED = 42
DEFAULT_WARMUP_STEPS = 0

# Optimizer defaults
DEFAULT_LEARNING_RATE = 1e-4
DEFAULT_WEIGHT_DECAY = 0.01
DEFAULT_ADAM_EPS = 1e-8
DEFAULT_ADAM_BETAS = (0.9, 0.999)

# Gradient clipping defaults
DEFAULT_GRADIENT_CLIP_VALUE = 1.0
DEFAULT_GRADIENT_ACCUMULATION_STEPS = 1

# Mixed precision defaults
DEFAULT_INIT_SCALE = 2**16
DEFAULT_GROWTH_INTERVAL = 1000
DEFAULT_SCALE_FACTOR = 2.0
DEFAULT_MIN_SCALE = 1.0
DEFAULT_MAX_SCALE = 2**32

# Checkpointing defaults
DEFAULT_CHECKPOINT_INTERVAL = 1000
DEFAULT_CHECKPOINT_DIR = "./checkpoints"
DEFAULT_MAX_CHECKPOINTS = 5

# Memory management
DEFAULT_ACTIVATION_CHECKPOINT_CLEANUP = 1000
DEFAULT_CPU_OFFLOAD_THRESHOLD = 0.9  # 90% memory usage

# Parallelism defaults
DEFAULT_TREE_THRESHOLD = 1000
DEFAULT_CTA_SIZE = 8
DEFAULT_MIN_NCHANNELS = 4

# Performance monitoring
DEFAULT_PROFILE_WARMUP = 10
DEFAULT_PROFILE_ACTIVE = 100
DEFAULT_PROFILE_REPEAT = 1

# Timeout values (in seconds)
DEFAULT_INIT_TIMEOUT = 300
DEFAULT_BARRIER_TIMEOUT = 30
DEFAULT_CLEANUP_TIMEOUT = 30

# Buffer sizes
DEFAULT_COMM_BUFFER_SIZE = 1024 * 1024 * 256  # 256MB
DEFAULT_GRADIENT_BUFFER_SIZE = 1024 * 1024 * 512  # 512MB
