#!/bin/bash
codex --search exec --dangerously-bypass-approvals-and-sandbox  \
  -m gpt-5.2 -c model_reasoning_effort="xhigh" \
  'In the gemm_cuda directory, exhaust every reasonable possibility while strictly avoiding Tensor Core features. Progressively optimize an FP32 SGEMM kernel until it performs at least as well as, and ideally better than, cuBLAS. The cuBLAS SGEMM implementation should not use Tensor Cores, so your implementation must not use them either. Explore the design space thoroughly and optimize in clearly separated steps, with one file per optimization. Keep the diff between adjacent optimization files as clear and readable as possible. There is no upper limit on the number of optimization iterations. For every step, benchmark against cuBLAS and plot the performance comparison. You may use gemm2 as a reference, but the methodology must be as scientific and defensible as possible and follow common industry benchmarking practice. Record every experiment command, result, and corresponding detailed analysis in a Markdown report. The final implementation must at least match, and preferably exceed, cuBLAS performance. Target only the GPU installed in the current machine. You may search the Internet for any relevant material. Useful starting points include https://salykova.github.io/gemm-gpu and every linked GitHub repository, blog post, or other resource. Cite any implementation that informs an optimization. Do not constrain yourself to conventional techniques; seek novel approaches that can make the kernel exceptionally fast. You may use any tools, including ncu. The report may include extremely detailed measurements, proposed techniques, validation procedures, and analysis.'

codex --search exec --dangerously-bypass-approvals-and-sandbox  \
  -m gpt-5.2 -c model_reasoning_effort="xhigh" \
  'In the gemm_tensor directory, exhaust every reasonable possibility and use Tensor Core features to progressively optimize a half-precision HGEMM kernel until it performs at least as well as, and ideally better than, cuBLAS. Because cuBLAS should use Tensor Cores for HGEMM, your implementation should use them as well. Explore the design space thoroughly and optimize in clearly separated steps, with one file per optimization. Keep the diff between adjacent optimization files as clear and readable as possible. There is no upper limit on the number of optimization iterations. For every step, benchmark against cuBLAS and plot the performance comparison. You may use gemm2 as a reference, but the methodology must be as scientific and defensible as possible and follow common industry benchmarking practice. Record every experiment command, result, and corresponding detailed analysis in a Markdown report. The final implementation must at least match, and preferably exceed, cuBLAS performance. Target only the GPU installed in the current machine. You may search the Internet for any relevant material. Useful starting points include https://salykova.github.io/gemm-gpu and every linked GitHub repository, blog post, or other resource. Cite any implementation that informs an optimization. Do not constrain yourself to conventional techniques; seek novel approaches that can make the kernel exceptionally fast. You may use any tools, including ncu. The report may include extremely detailed measurements, proposed techniques, validation procedures, and analysis.'

codex --search exec --dangerously-bypass-approvals-and-sandbox  \
  -m gpt-5.2 -c model_reasoning_effort="xhigh" \
  'In the flashattn directory, exhaust every reasonable possibility and progressively optimize an attention kernel until it outperforms the renowned production-grade FlashAttention repository and its fastest implementation. Explore the entire design space and optimize in clearly separated steps, with one file per optimization. Keep the diff between adjacent optimization files as clear and readable as possible. There is no upper limit on the number of optimization iterations. For every step, benchmark against the high-performance production FlashAttention repository and plot the performance comparison. You may use gemm2 as a reference, but the methodology must be as scientific and defensible as possible and follow common industry benchmarking practice. Record every experiment command, result, and corresponding detailed analysis in a Markdown report. The original target requires the final implementation to at least match, and preferably exceed, cuBLAS performance. Target only the GPU installed in the current machine. You may search the Internet for any relevant material and clone any Git repositories needed for source analysis. First inspect repositories already present under /data/projects and /data2/projects, and download missing repositories only when necessary. Cite any implementation that informs an optimization. Do not constrain yourself to conventional techniques; seek novel approaches that can make the kernel exceptionally fast. You may use any tools, including ncu. The report may include extremely detailed measurements, proposed techniques, validation procedures, and analysis.'
