training:
  seed: 42
  logging_level: DEBUG

model:
  path: Qwen/Qwen2.5-0.5B
  revision: main
  torch_dtype: bfloat16
  # Can be: eager, flash_attention_2, sdpa
  attn_implementation: flash_attention_2 
  gradient_checkpointing: true

dataset:
  # https://huggingface.co/datasets/DigitalLearningGmbH/MATH-lighteval
  path: DigitalLearningGmbH/MATH-lighteval
  name: default
  train_split: train
  eval_split: test
