training:
  seed: 42
  logging_level: DEBUG

model:
  path: Qwen/Qwen2.5-0.5B
  revision: main
  torch_dtype: bfloat16
  attn_implementation: flash_attention_2
  gradient_checkpointing: true
  trust_remote_code: true

dataset:
  # https://huggingface.co/datasets/DigitalLearningGmbH/MATH-lighteval
  path: DigitalLearningGmbH/MATH-lighteval
  name: default
  train_split: train
  eval_split: test
