name: Tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - run: pip install torch==2.5.1 --extra-index-url https://download.pytorch.org/whl/cpu
      - run: pip install -e ".[test]"
      - run: pytest
